// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_U6GZhM7d_rmhwolwrU-8RuuCA1ofQW0',
    appId: '1:237157165536:web:7e4342476b5be02a01e385',
    messagingSenderId: '237157165536',
    projectId: 'barakaa-pharmacy',
    authDomain: 'barakaa-pharmacy.firebaseapp.com',
    storageBucket: 'barakaa-pharmacy.firebasestorage.app',
    measurementId: 'G-EBER872R4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3ITi1wGuS-aBDC6D-wEqxoYYTQyQpT4',
    appId: '1:237157165536:android:897c7d5fcfaa840501e385',
    messagingSenderId: '237157165536',
    projectId: 'barakaa-pharmacy',
    storageBucket: 'barakaa-pharmacy.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0ksz49MlnSiW7e3VELlWZeNW2MgYrMg',
    appId: '1:237157165536:ios:f759c97ffa27031701e385',
    messagingSenderId: '237157165536',
    projectId: 'barakaa-pharmacy',
    storageBucket: 'barakaa-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.barakaa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0ksz49MlnSiW7e3VELlWZeNW2MgYrMg',
    appId: '1:237157165536:ios:f759c97ffa27031701e385',
    messagingSenderId: '237157165536',
    projectId: 'barakaa-pharmacy',
    storageBucket: 'barakaa-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.barakaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_U6GZhM7d_rmhwolwrU-8RuuCA1ofQW0',
    appId: '1:237157165536:web:42b21d9ec37954f301e385',
    messagingSenderId: '237157165536',
    projectId: 'barakaa-pharmacy',
    authDomain: 'barakaa-pharmacy.firebaseapp.com',
    storageBucket: 'barakaa-pharmacy.firebasestorage.app',
    measurementId: 'G-LDKF1MEH5Q',
  );
}
